FROM joyzoursky/python-chromedriver

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# install chromedriver
RUN apt-get install -yqq unzip
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# set display port to avoid crash
ENV DISPLAY=:99

#upgrade pip
RUN /usr/local/bin/python -m pip install --upgrade pip

#creating app directory in container (linux machine)
RUN mkdir c:\home\web_scraper

#copying main.py from local directory to container's app directory
COPY main.py /home/web_scraper/main.py
COPY requirements.txt /home/web_scraper/requirements.txt
COPY price_links.csv /home/web_scraper/price_links.csv

#updating project references
#CMD pip install bs4
#CMD pip install selenium
#CMD pip install urllib3
RUN pip install -r /home/web_scraper/requirements.txt

#running main.py in container
CMD python /home/web_scraper/main.py